version: '3'

services:
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
      
  testebackend:
    build:  .
    command: npm start
    ports: 
      - "8080:8080"
    volumes:
      - .:/app